- name: Consul Container is running
  docker_container:
    name: "consul"
    image: consul
    hostname: "{{ ansible_hostname }}"
    network_mode: host
    command: docker-entrypoint.sh agent {{ consul_extra }} {{ consul_join }} -node={{ ansible_hostname }} -client=0.0.0.0 -bind={{ inventory_hostname }}
    ports:
     - "8500:8500"
     - "8600:8600/udp"    
  tags: [consul]
