- name: Download consul template zip
  get_url:
    url: "{{ consul_template_download_url }}"
    dest: "{{ consul_template_tmp_zip }}"
  tags: [consul-template]

- name: Extract consul template zip
  unarchive:
    remote_src: yes
    src: "{{ consul_template_tmp_zip }}"
    dest: /usr/local/bin
  tags: [consul-template]
    
- name: Directory is created
  file:
    path: /data/consul-template
    state: directory
  tags: [consul-template]
  
- name: Templates are copied
  copy:
    src: "{{ item }}"
    dest: "/data/consul-template/{{ item }}"
    mode: 0644
  with_items:
    - apache_php_api.ctmpl
    - nginx_locations_php_api.ctmpl
    - nginx_upstreams_php_api.ctmpl
    - regenerate-nginx-config.sh
    - haproxy_php_api.ctmpl
    - regenerate-haproxy-config.sh
  tags: [consul-template]


