- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: "{{ directories }}"
  tags: [haproxy]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  register: result
  tags: [haproxy]

- name: Container is running
  docker_container:
    image: haproxy
    name: haproxy
    state: started
    ports: "{{ ports }}"
    volumes: /data/haproxy/config/:/usr/local/etc/haproxy/
  tags: [haproxy]
