version: "3.2"
services:
  php1:
    build: 
      context: './php1/'
      args:
       PHP_VERSION: 7.3
    ports:
      - "9000"
    environment:
      - SERVICE_NAME=php1
      - SERVICE_ID=php1
      - SERVICE_TAGS=php_api
      - SERVICE_RULE=/php1
  php2:
    build: 
      context: './php2/'
      args:
       PHP_VERSION: 7.3
    ports:
      - "9000"
    environment:
      - SERVICE_NAME=php2
      - SERVICE_ID=php2
      - SERVICE_TAGS=php_api
      - SERVICE_RULE=/php2

