- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/apache/sites-enabled
  tags: [php1]
  
- name: Apache vhost copies
  copy:
    src: "{{ item }}"
    dest: "/data/apache/sites-enabled/{{ item }}"
    mode: 0644
  with_items:
    - 000-default.conf
  tags: [php1]
  
- name: Build php1 image
  docker_image:
    name: php1
    build:
      path: /vagrant/app/php1
      args:
        PHP_VERSION: 7.3
    source: build
    
- name: php1 start
  docker_container:
    name: php1
    image: php1
    ports:
     - "80"
    volumes: "{{ apache_volumes }}"
    env:
      SERVICE_NAME=php1
      SERVICE_ID=php1
      SERVICE_TAGS=php_api
      SERVICE_RULE=/php1
      SERVICE_DEST=/api/php1
      SERVICE_HOST={{ inventory_hostname }}
    state: started
  tags: [php1]
